name: Deploy/destroy AWS infrastructure for Cocktail Master project

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Cocktail master image version to deploy"
        required: false
        default: "latest"
      mode:
        description: "'create' or 'destroy' infrastructure"
        required: false
        default: "create"

# job definitions
jobs:
  create-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.mode == 'create' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate -no-color
      - name: Terraform Apply
        run: |
          terraform apply -var="db_username=${{ secrets.DB_USERNAME }}" \
          -var="db_password=${{ secrets.DB_PASSWORD }}" \
          -var="django_key=${{ secrets.DJANGO_SECRET_KEY }}" \
          -var="image_tag=${{ github.event.inputs.image_tag }}" -auto-approve
      - name: Output IP address of the application
        run: echo "IP_ADDRESS=$(terraform output -json ecs-public-ips | jq -r '.[0]')" >> $GITHUB_ENV
      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            CREATE-JOB for *Cocktail Master Infra v ${{ github.event.inputs.image_tag }}*
            completed with a *${{ JOB.STATUS }}*
            URL: http://${{ env.IP_ADDRESS }}

  destroy-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.mode == 'destroy' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate -no-color
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            DESTROY-JOB for *Cocktail Master Infra*
            completed with a *${{ JOB.STATUS }}*
